#@data/values
---
#! build metadata
VERSION: "1.0.0"
COMMIT: "0000000000000000000000000000000000000000"
BRANCH: "master"

#! configurables
namespace: "demo"
imagePullPolicy: IfNotPresent
introspect_labels:
  app: "introspect"
  visualize: "true"
mongodb_port: 27017
mongodb_labels:
  app: "mongodb"
persistent: false
pvc_size: "5Gi"
hpa: true
ingress: false
ingress_class: "nginx"
istio: false
cert_issuer: "myissuer-staging"
ingress_dns: "introspect.ingress.example.com"
host_dns: "*.ingress.example.com"
istio_gw: "istio-system/garden_gw"
