apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  type: target
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: namespace
  type: data
  schema:
    type: string

- name: password
  type: data
  schema:
    type: string

- name: username
  type: data
  schema:
    type: string

subinstallationExecutions:
- name: application
  type: GoTemplate
  template: |
    subinstallations:
    - apiVersion: landscaper.gardener.cloud/v1alpha1
      kind: InstallationTemplate
      name: mongodb
      blueprint:
        ref: cd://componentReferences/mongodb/resources/mongodb-blueprint
      imports:
        targets:
        - name: cluster
          target: cluster
      importDataMappings:
        namespace:    {{ .imports.namespace }}
        rootPassword: {{ .imports.password }}
      exports:
        data:
        - name: connection
          dataRef: "mongodb-connection"
    
    - apiVersion: landscaper.gardener.cloud/v1alpha1
      kind: InstallationTemplate
      name: introspect
      blueprint:
        ref: cd://componentReferences/introspect/resources/introspect-blueprint
      imports:
        targets:
        - name: cluster
          target: cluster
        data:
        - name: connection
          dataRef: mongodb-connection
      importDataMappings:
        namespace:    {{ .imports.namespace }}
        username:     {{ .imports.username }}
        password:     {{ .imports.password }}
