kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
#featureGates:
#  "CSIMigration": true
#runtimeConfig:
#  "api/alpha": "false"
networking:
  apiServerPort: 6443
  kubeProxyMode: "ipvs"
#  ipFamily: dual
#  apiServerAddress: 127.0.0.1
#  podSubnet: "10.244.0.0/16"
#  serviceSubnet: "10.96.0.0/12"
#  # the default CNI will not be installed
#  disableDefaultCNI: true 
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "kubernetes.docker.internal"
        - "gateway.docker.internal"
        - "localhost"
        - "127.0.0.1"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
#  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
#- role: worker
#  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
#- role: worker
#  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
#- role: worker
#  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
#  # add a mount from /path/to/my/files on the host to /files on the node
#  extraMounts:
#  - hostPath: /path/to/my/files
#    containerPath: /files
#  #
#  # add an additional mount leveraging *all* of the config fields
#  #
#  # generally you only need the two fields above ...
#  #
#  - hostPath: /path/to/my/other-files/
#    containerPath: /other-files
#    # optional: if set, the mount is read-only.
#    # default false
#    readOnly: true
#    # optional: if set, the mount needs SELinux relabeling.
#    # default false
#    selinuxRelabel: false
#    # optional: set propagation mode (None, HostToContainer or Bidirectional)
#    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
#    # default None
#    #
#    # WARNING: You very likely do not need this field.
#    #
#    # This field controls propagation of *additional* mounts created
#    # *at runtime* underneath this mount.
#    #
#    # On MacOS with Docker Desktop, if the mount is from macOS and not the
#    # docker desktop VM, you cannot use this field. You can use it for
#    # mounts to the linux VM.
#    propagation: None
#  # port forward 80 on the host to 80 on this node
#  extraPortMappings:
#  - containerPort: 80
#    hostPort: 80
#    # optional: set the bind address on the host
#    # 0.0.0.0 is the current default
#    listenAddress: "127.0.0.1"
#    # optional: set the protocol to one of TCP, UDP, SCTP.
#    # TCP is the default
#    protocol: TCP
#
