apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: introspect
profiles:
- name: kind
  build:
    local:
      push: false
  activation:
  - kubeContext: "kind-kind"
- name: docker-desktop
  build:
    local:
      push: false
  activation:
  - kubeContext: "docker-desktop"
build:
  artifacts:
    - image: ghcr.io/vasu1124/introspect
      hooks:
        before:
          - command: ["make", "introspect-linux"]
      runtimeType: go
      context: .
      docker:
        dockerfile: docker/Dockerfile.alpine
        cacheFrom:
        - ghcr.io/vasu1124/introspect
      sync:
        manual:
          - src: 'introspect-linux'
            dest: '/'
          - src: 'tmpl/**'
            dest: '/'
          - src: 'css/**'
            dest: '/'
  tagPolicy:
    envTemplate:
      template: '{{.gitVersion}}'
manifests:
  kustomize:
    paths:
      - kubernetes/all-in-one
deploy:
  kubectl: {}
portForward:
- resourceType: service
  resourceName: introspect
  namespace: default
  port: 9090
  localPort: 9090