apiVersion: v1
kind: ConfigMap
metadata:
  name: introspect-config
data:
  config.json: |+
    {
      "DBtype": "mongodb",
      "Addrs": ["mongodb:27017"],
      "Database": "guestbook",
      "Timeout": 5000000000,
      "FailFast": true,

      "Endpoints":   ["etcd:2379"],
      "DialTimeout": 5000000000
    }
  example.yaml: |+
    foo: bar
    exact: true
    timeout: 18