apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: introspect-lease
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: introspect-lease-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: introspect-lease
subjects:
- kind: ServiceAccount
  name: default
  namespace: default