apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../pkg/operator/useless/config/crd/
- ../../pkg/operator/useless/config/rbac/

# list of Resource Config to be Applied
resources:
- config.yaml
- deployment.yaml
- service.yaml

# labels added to all Resources
commonLabels:
  app: introspect
