apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- ../../pkg/operator/useless/config/crd/
- ../../pkg/operator/useless/config/rbac/
- config.yaml
- deployment.yaml
- service.yaml
- introspect-tls.yaml
- introspect-validatingwh.yaml
- secret.yaml
# - uselessmachine-1.yaml
# - uselessmachine-2.yaml

# labels added to all Resources
commonLabels:
  app: introspect
