apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "introspect.fullname" . }}-config
data:
  config.json: |+
    {
      "Addrs": ["{{ .Values.mongodb }}"],
      "Database": "guestbook",
      "Timeout": 5000000000,
      "FailFast": true
    }
  example.yaml: |+
    foo: bar
    exact: true
    timeout: 18