apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "introspect.fullname" . }}-config
data:
  config.json: |+
    {
      "DBType": "mongodb",

      "Addrs": ["{{ .Values.mongodb.connect }}"],
      "Timeout": 5000000000,
      "FailFast": true,

      "Endpoints":   ["etcd:2379"],
      "DialTimeout": 5000000000
    }
  example.yaml: |+
    foo: bar
    exact: true
    timeout: 18