apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "introspect.fullname" . }}-lease-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "introspect.fullname" . }}-lease
subjects:
- kind: ServiceAccount
  name: {{ include "introspect.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
