apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "introspect.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "introspect.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "introspect.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
