apiVersion: v1
kind: Secret
metadata:
  name: {{ include "introspect.fullname" . }}-secret
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc}}
  username: {{ .Values.auth.username | b64enc}}
