apiVersion: v1
kind: Service
metadata:
  name: {{ include "introspect.fullname" . }}
  labels:
    {{- include "introspect.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    prometheus.io/path: '/metrics'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "introspect.selectorLabels" . | nindent 4 }}
