apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: introspect-base
spec:
  destination: 
    name: introspect
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0