apiVersion: v1
kind: Pod
metadata:
  name: introspect
  labels:
    app: introspect
spec:
  containers:
  - image: vasu1124/introspect:1.0.0
#    imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    name: introspect
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    resources:
      requests:
        cpu: 500m
      limits:
        cpu: 1000m
    livenessProbe:
   # an http probe
      httpGet:
        path: /healthz
        port: 9090
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
  # an http probe
      httpGet:
        path: /healthzr
        port: 9090
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 1
      failureThreshold: 2
 