apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: introspect-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: useless
    app.kubernetes.io/part-of: useless
    app.kubernetes.io/managed-by: kustomize
  name: introspect-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uselessmachine-editor-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
