apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: useless-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: useless
    app.kubernetes.io/part-of: useless
    app.kubernetes.io/managed-by: kustomize
  name: useless-manager
  namespace: system
