# permissions for end users to edit uselessmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uselessmachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: useless
    app.kubernetes.io/part-of: useless
    app.kubernetes.io/managed-by: kustomize
  name: uselessmachine-editor-role
rules:
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselessmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselessmachines/status
  verbs:
  - get
