name: Build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build with Docker buildx
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io      
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/introspect
      # linux/arm64
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm/v7 

    steps:

    - name: Check out cache
      uses: actions/cache@v1
      with:
        path: |
          ~/go/pkg/mod
          ~/vendor
          /tmp/.buildx-cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
      id: buildx
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Check out code
      uses: actions/checkout@v1
    
    - name: go mod vendor
      run: go mod vendor

    - name: Login to DockerHub
      if: success()
      uses: crazy-max/ghaction-docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Buildx (build+push) v1.0
      if: success()
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --output "type=image,push=true" \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:v1.0 \
          --build-arg VERSION=v1.0 \
          --build-arg COMMIT=${{github.sha}} \
          --build-arg BRANCH=${GITHUB_REF##*/} \
          --file ./Dockerfile .

    - name: Inspect image
      if: success()
      run: |
        docker buildx imagetools inspect ${DOCKER_IMAGE}:v1.0

    - name: Docker Buildx (build+push) v2.0
      if: success()
      run: |
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --output "type=image,push=true" \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:v2.0 \
          --build-arg VERSION=v2.0 \
          --build-arg COMMIT=${{github.sha}} \
          --build-arg BRANCH=${GITHUB_REF##*/} \
          --file ./Dockerfile .

    - name: Inspect image
      if: success()
      run: |
        docker buildx imagetools inspect ${DOCKER_IMAGE}:v2.0