name: Build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check out cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Build v1.0
      run: go build -v -ldflags "-X github.com/vasu1124/introspect/pkg/version.Version=v1.0 -X github.com/vasu1124/introspect/pkg/version.Commit=${{github.sha}} -X github.com/vasu1124/introspect/pkg/version.Branch=${{github.ref}}" -o introspect-linux-amd64 ./cmd/introspect

    - name: Build Docker image v1.0
      if: success()
      run: docker build --file docker/Dockerfile.alpine --tag vasu1124/introspect:v1.0 .
    
    - name: Log into registry
      if: success()
      run: docker login -u vasu1124 -p ${{secrets.docker_token}}

    - name: Push Docker image v1.0
      if: success()
      run: docker push vasu1124/introspect:v1.0

    - name: Build v2.0
      run: go build -v -ldflags "-X github.com/vasu1124/introspect/pkg/version.Version=v2.0 -X github.com/vasu1124/introspect/pkg/version.Commit=${{github.sha}} -X github.com/vasu1124/introspect/pkg/version.Branch=${{github.ref}}" -o introspect-linux-amd64 ./cmd/introspect

    - name: Build Docker image v2.0
      if: success()
      run: docker build --file docker/Dockerfile.alpine --tag vasu1124/introspect:v2.0 .
    
    - name: Push Docker image v2.0
      if: success()
      run: docker push vasu1124/introspect:v2.0
