name: Build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build with Docker buildx
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io      
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/introspect
      # linux/arm64
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm/v7 

    steps:

    - name: Check out cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/vendor
          /tmp/.buildx-cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64,linux/arm/v7

    - name: Set up Docker Buildx      
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
      id: buildx

    - name: Check out code
      uses: actions/checkout@v1
    
    - name: go mod vendor
      run: go mod vendor

    - name: Login to DockerHub
      if: success()
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Buildx (build+push) v1.0
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7
        push: true
        tags: vasu1124/introspect:v1.0
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: VERSION=v1.0,COMMIT=${{github.sha}},BRANCH=${GITHUB_REF##*/}
        file: ./Dockerfile

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Inspect image
      if: success()
      run: |
        docker buildx imagetools inspect ${DOCKER_IMAGE}:v1.0


    - name: Docker Buildx (build+push) v2.0
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7
        push: true
        tags: vasu1124/introspect:v2.0
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: VERSION=v2.0,COMMIT=${{github.sha}},BRANCH=${GITHUB_REF##*/}
        file: ./Dockerfile

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Inspect image
      if: success()
      run: |
        docker buildx imagetools inspect ${DOCKER_IMAGE}:v2.0