name: Go
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build v1.0
      run: go build -v -ldflags "-X github.com/vasu1124/introspect/pkg/version.Version=v1.0 -X github.com/vasu1124/introspect/pkg/version.Commit={{github.sha}} -X github.com/vasu1124/introspect/pkg/version.Branch={{github.ref}}" -o introspect-linux-amd64 ./cmd/introspect
