name: Go
on:
  push:
    branches:
    - master
    - release/*

env:
  DOCKERREPO: vasu1124

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build v1.0
      run: go build -v -ldflags "-X github.com/vasu1124/introspect/pkg/version.Version=v1.0 -X github.com/vasu1124/introspect/pkg/version.Commit=${{github.sha}} -X github.com/vasu1124/introspect/pkg/version.Branch=${{github.ref}}" -o introspect-linux-amd64 ./cmd/introspect

    - name: Build v1.0 the Docker image
      if: success()
      run: docker build --file docker/Dockerfile.alpine --tag ${{DOCKERREPO}}/introspect:v1.0
    
    - name: Log into registry
      if: success()
      run: docker login -u ${{DOCKERREPO}} -p ${{docker_token}}

    - name: Push v1.0 the Docker image
      if: success()
      run: docker push ${{DOCKERREPO}}/introspect:v1.0
